config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create', as: :title
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  get 'tasks/:id', to: 'tasks#show', as: :task
  delete "tasks/:id", to: "tasks#destroy", as: :destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_task, only: [:show]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    # create new instance of restaurant
    @task = Task.new
  end

  def create
    # save a new instance of restaurant with user-given parameters
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path(@tasks)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    # redirecting to the path of this specific instance
    redirect_to tasks_path(@tasks)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path(@tasks)
  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details)
  end

  # def set_task
  #   @task = Task.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<!-- The Rails Way -->

app/views/tasks/edit.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<% @tasks.each do |task|%>
  <%= link_to task.title, task_path(task.id) %>
  <%= link_to "Delete", task_path(task.id),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<% end %>
  

app/views/tasks/new.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<%= @task.title %>
<%= @task.details %>
<br>
<%= link_to "Back to list", tasks_path  %>
<br>
<%= link_to "Edit this task !", edit_path(@task.id) %>